In [361]:
import networkx as nx
import os
import scipy as sp
import numpy
import math

In [362]:
#read in graph
G = nx.read_gml(str(os.getcwd())+"/polblogs.gml")

In [363]:
# convert to undirected
G = G.to_undirected()

In [364]:
# adjacency matrix
G_mat = nx.adjacency_matrix(G)

In [365]:
# get degrees
G_mat.sum(axis=1)

matrix([[26],
        [45],
        [ 0],
        ..., 
        [ 1],
        [18],
        [ 1]])

In [366]:
# get number of edges
M = G_mat.sum()/2
print(M)

16781


In [367]:
num_nodes = len(G_mat.sum(axis=1))
print num_nodes

1490


In [368]:
# create vector holding node degrees
deg_vec = sp.sparse.csr_matrix((G_mat.sum(axis=1)))
# get transpose
deg_vec_transpose = sp.sparse.csr_matrix.transpose(deg_vec)

In [369]:
# multiply degree vectors to get matrix of k_i * k_j
deg_matrix = deg_vec*deg_vec_transpose

In [370]:
# divide by number of edges
deg_matrix = deg_matrix/M

In [371]:
# modularity matrix
modu_matrix = G_mat - deg_matrix

In [372]:
# find leading eigenvalue and eigenvector of modularity matrix
eigenvalues = sp.sparse.linalg.eigsh(modu_matrix,k=1, which='LA')

In [373]:
# negative eigenvalues classified as -1, positive eigenvalues classified as 1
classification = (eigenvalues[1])*(1/abs(eigenvalues[1]))
print classification

[[-1.]
 [-1.]
 [-1.]
 ..., 
 [ 1.]
 [ 1.]
 [ 1.]]


In [374]:
# convert to array
classification_iter = (float(i) for i in classification)
classification_array = numpy.fromiter(classification_iter, numpy.float)
classification_array

array([-1., -1., -1., ...,  1.,  1.,  1.])

In [377]:
# array of true types 
# (need to match however groups are given during classification)
iterable = (-1 if G.node[i]['value']==0 else 1 for i in range(1,1491) )
true_types = numpy.fromiter(iterable, numpy.float)
print true_types

[-1. -1. -1. ...,  1.  1.  1.]


In [381]:
# percent correct
float(sum(eval))/float(len(eval))

0.8697986577181208